name: pavan_agro
description: "Pavan HiTech Agro App."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.1
  image_picker: ^1.2.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  android_id: ^0.5.1
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
